msbuild "2sem\lb1\1 Task\1 Task.vcxproj"
msbuild "2sem\lb2\1 Task\1 Task\1 Task.vcxproj"
msbuild "2sem\lb2\Decompressor\Decompressor\Decompressor\Decompressor.vcxproj"
msbuild "2sem\lb3\1 Task\1 Task\1 Task.vcxproj"
msbuild "2sem\lb4\Task 1\Task 1\Task 1.vcxproj"
msbuild "2sem\lb5\Task 1\Task 1\Task 1.vcxproj"
